apiVersion: v1
kind: LimitRange
metadata:
  name: ex280-limits
  namespace: bluebook
spec:
  limits:
  - type: Container
    defaultRequest:
      memory: 100Mi
      cpu: 100m
    min:
      memory: 100Mi
      cpu: 10m
    max:
      memory: 300Mi
      cpu: 500m
  - type: Pod
    min:
      memory: 100Mi
      cpu: 10m
    max:
      memory: 300Mi
      cpu: 500m
