apiVersion: v1
kind: LimitRange
metadata:
  name: rocky-limits
  namespace: rocky
spec:
  limits:
  - type: Pod
    max:
      memory: 300Mi
      cpu: 300m
    min:
      memory: 5Mi
      cpu: 5m
  - type: Container
    max:
      memory: 300Mi
      cpu: 400m
    min:
      memory: 5Mi
      cpu: 5m
    default:
      memory: 100Mi
      cpu: 100m